name: first workflow

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build_and_push:
    name: Build, test and push Docker image
    runs-on: ubuntu-latest

    steps:
        - 
            name: Check out the repository
            uses: actions/checkout@v4

        - 
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3

        - 
            name: Set up QEMU
            uses: docker/setup-qemu-action@v3

        - 
            name: Docker metadata
            id: meta
            uses: docker/metadata-action@v5
            with:
                images: |
                    ghcr.io/${{ github.repository_owner }}/zad2
                    docker.io/${{ vars.DOCKERHUB_USERNAME }}/zad2
                flavor: latest=false
                tags: |
                    type=semver,pattern={{version}}
                    type=sha,format=short,prefix=sha-

        - 
            name: Log in to GHCR
            uses: docker/login-action@v3
            with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GIT_TOKEN }}

        - 
            name: Log in to DockerHub
            uses: docker/login-action@v3
            with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

        - 
            name: Build amd64 image (local)
            uses: docker/build-push-action@v5
            with:
                context: .
                file: ./Dockerfile
                platforms: linux/amd64
                load: true
                cache-from: |
                    type=registry,ref=docker.io/${{ vars.DOCKERHUB_USERNAME }}/zad2:cache-amd64
                cache-to: |
                    type=registry,ref=docker.io/${{ vars.DOCKERHUB_USERNAME }}/zad2:cache-amd64,mode=max
                tags: zad2:test-amd64

        - 
            name: Scan amd64 image
            uses: aquasecurity/trivy-action@0.28.0
            with:
                image-ref: zad2:test-amd64
                format: 'table'
                severity: 'CRITICAL,HIGH'
                ignore-unfixed: true
                exit-code: '1'

        - 
            name: Build arm64 image (local)
            uses: docker/build-push-action@v5
            with:
                context: .
                file: ./Dockerfile
                platforms: linux/arm64
                load: true
                cache-from: |
                    type=registry,ref=docker.io/${{ vars.DOCKERHUB_USERNAME }}/zad2:cache-arm64
                cache-to: |
                    type=registry,ref=docker.io/${{ vars.DOCKERHUB_USERNAME }}/zad2:cache-arm64,mode=max
                tags: zad2:test-arm64

        - 
            name: Scan arm64 image
            uses: aquasecurity/trivy-action@0.28.0
            with:
                image-ref: zad2:test-arm64
                format: 'table'
                severity: 'CRITICAL,HIGH'
                ignore-unfixed: true
                exit-code: '1'

        - 
            name: Rebuild and push multi-arch image to GHCR
            if: success()
            uses: docker/build-push-action@v5
            with:
                context: .
                file: ./Dockerfile
                platforms: linux/amd64,linux/arm64
                push: true
                cache-from: |
                    type=registry,ref=docker.io/${{ vars.DOCKERHUB_USERNAME }}/zad2:cache-amd64
                    type=registry,ref=docker.io/${{ vars.DOCKERHUB_USERNAME }}/zad2:cache-arm64
                cache-to: |
                    type=registry,ref=docker.io/${{ vars.DOCKERHUB_USERNAME }}/zad2:cache-amd64,mode=max
                    type=registry,ref=docker.io/${{ vars.DOCKERHUB_USERNAME }}/zad2:cache-arm64,mode=max
                tags: ${{ steps.meta.outputs.tags }}